CREATE TABLE RaceCourse(
	CourseID		UNIQUEIDENTIFIER	PRIMARY KEY,
	CourseAddress	NVARCHAR(50),
	CourseName		NVARCHAR(max)	NOT NULL,
	CoursePhone		INT
	);

CREATE TABLE Meeting(
	MeetingID		UNIQUEIDENTIFIER	PRIMARY KEY,
	CourseID		UNIQUEIDENTIFIER	FOREIGN KEY REFERENCES RaceCourse(CourseID),
	MDate			DATE		NOT NULL,
	JetBetCode		INT			NOT NULL,
	TrackDirection	NVARCHAR(15)	
	);
	
CREATE TABLE Class(
	ClassID			UNIQUEIDENTIFIER	PRIMARY KEY,
	ClassDesc		NVARCHAR(20)	NOT NULL
	);
	
CREATE TABLE Race(
	RaceID			UNIQUEIDENTIFIER	Primary Key,	
	RaceName		NVARCHAR(50)	NOT NULL,
	RaceNum			INT			NOT NULL,
	MeetingID		UNIQUEIDENTIFIER,
	Distance		INT,
	Stake			NNVARCHAR(50),
	TrackCondition	NVARCHAR(10),
	Weather			NVARCHAR(10),		
	Foreign Key (MeetingID) REFERENCES Meeting(MeetingID)	
	);
	
CREATE TABLE BetType(
	BetTypeID		UNIQUEIDENTIFIER	PRIMARY KEY,
	BetTypeDesc		NVARCHAR(20),
	);
	
CREATE TABLE Bet(
	BetID			UNIQUEIDENTIFIER	PRIMARY KEY,
	BetTypeID		UNIQUEIDENTIFIER	FOREIGN KEY REFERENCES BetType(BetTypeID),
	RaceID			UNIQUEIDENTIFIER	FOREIGN KEY	REFERENCES Race(RaceID),
	);
	
CREATE TABLE Horse(
	HorseID			UNIQUEIDENTIFIER	PRIMARY KEY,
	HorseName		NVARCHAR(20)	NOT NULL,
	StakesWon		MONEY
	);
	
CREATE TABLE HorseInRace(
	EntryID			UNIQUEIDENTIFIER	PRIMARY KEY,
	HorseID			UNIQUEIDENTIFIER	FOREIGN KEY REFERENCES Horse(HorseID),
	RaceID			UNIQUEIDENTIFIER	FOREIGN KEY REFERENCES Race(RaceID),
	Scratched		INT,
	Jockey			NVARCHAR(20),
	Barrier			NVARCHAR(5),
	JockeyWeight	DECIMAL,
	Name			NVARCHAR(20)			
	);
	
CREATE TABLE HorseInBet(
	HorseBetID		UNIQUEIDENTIFIER	PRIMARY KEY,
	EntryID			UNIQUEIDENTIFIER	FOREIGN KEY REFERENCES HorseInRace(EntryID)
	);
	
CREATE TABLE BetLines(
	BetLineID		UNIQUEIDENTIFIER	PRIMARY KEY,
	HorseInBetID	UNIQUEIDENTIFIER	FOREIGN KEY REFERENCES HorseInBet(HorseBetID),
	BetID			UNIQUEIDENTIFIER					FOREIGN KEY REFERENCES Bet(BetID),
	Position		INT					Not Null
	);
	