USE WagerWatcher

BEGIN TRANSACTION
CREATE TABLE RaceCourse(
	CourseID		UNIQUEIDENTIFIER	PRIMARY KEY,
	CourseAddress	NVARCHAR(50),
	CourseName		NVARCHAR(MAX)	NOT NULL,
	CoursePhone		INT
	);

CREATE TABLE Meeting(
	MeetingID		UNIQUEIDENTIFIER	PRIMARY KEY,
	CourseID		UNIQUEIDENTIFIER	FOREIGN KEY REFERENCES RaceCourse(CourseID),
	MDate			NVARCHAR(50)		NOT NULL,
	JetBetCode		INT					NOT NULL,
	TrackDirection	NVARCHAR(15),
	BetSlipType		NVARCHAR(50),
	Code			NVARCHAR(50),
	Country			NVARCHAR(50),
	Name			NVARCHAR(50),
	Penetrometer	NVARCHAR(50),
	MeetingStatus	NVARCHAR(50),
	RaceType		NVARCHAR(50),
	Venue			NVARCHAR(50)
	);
	
CREATE TABLE Class(
	ClassID			UNIQUEIDENTIFIER	PRIMARY KEY,
	ClassDesc		NVARCHAR(20)	UNIQUE	NOT NULL
	);

CREATE TABLE Race(
	RaceID			UNIQUEIDENTIFIER	Primary Key,
	MeetingID		UNIQUEIDENTIFIER,
	ClassID			UNIQUEIDENTIFIER,	
	RaceName		NVARCHAR(50)		NOT NULL,
	RaceNum			INT					NOT NULL,
	Distance		INT,
	Stake			NVARCHAR(50),
	TrackCondition	NVARCHAR(10),
	Weather			NVARCHAR(10),		
	NormTime		NVARCHAR(50),
	OverseasNumber	NVARCHAR(50),
	RaceStatus		NVARCHAR(50),
	Venue			NVARCHAR(50),
	FOREIGN KEY (ClassID) REFERENCES Class(ClassID),
	Foreign Key (MeetingID) REFERENCES Meeting(MeetingID)
	);
	

CREATE TABLE Horse(
	HorseID			UNIQUEIDENTIFIER	PRIMARY KEY,
	HorseName		NVARCHAR(20)	NOT NULL,
	StakesWon		MONEY
	);

CREATE TABLE FixedOption(
	OptionID	UNIQUEIDENTIFIER	PRIMARY KEY,
	RaceID		UNIQUEIDENTIFIER,
	OptionNum	INT,
	BetType		NVARCHAR(50),
	FOREIGN KEY (RaceID) REFERENCES Race(RaceID)
	);
CREATE TABLE BetType(
	BetTypeID		UNIQUEIDENTIFIER	PRIMARY KEY,
	BetTypeDesc		NVARCHAR(20),
	XmlDesc			NVARCHAR(20)
	);
	
CREATE TABLE Pool(
	PoolID			UNIQUEIDENTIFIER	PRIMARY KEY,
	BetTypeID		UNIQUEIDENTIFIER	FOREIGN KEY REFERENCES BetType(BetTypeID),
	RaceID			UNIQUEIDENTIFIER	FOREIGN KEY REFERENCES Race(RaceID),
	Total			NVARCHAR(20),
	Gaurantee		NVARCHAR(20),
	BroughtForward	NVARCHAR(20),
	Commingled		NVARCHAR(5),
	CommingledInfo	NVARCHAR(20)
	);

CREATE TABLE Result(
	ResultID		UNIQUEIDENTIFIER	PRIMARY KEY,
	PoolID			UNIQUEIDENTIFIER	FOREIGN KEY REFERENCES Pool(PoolID),
	RaceDate		NVARCHAR(20),
	MeetingNum		INT,
	RaceNum			INT,
	HorseNum		INT,
	BetTypeDesc		NVARCHAR(10),
	AmountPaid		NVARCHAR(30)
	);

CREATE TABLE EntrantInResult(
	EntrantInResultID	UNIQUEIDENTIFIER	PRIMARY KEY,
	ResultID			UNIQUEIDENTIFIER	FOREIGN KEY REFERENCES Result(ResultID),
	HorseID				UNIQUEIDENTIFIER	FOREIGN KEY REFERENCES Horse(HorseID),
	Position			INT
	);

CREATE TABLE Bet(
	BetID			UNIQUEIDENTIFIER	PRIMARY KEY,
	PoolID			UNIQUEIDENTIFIER	FOREIGN KEY REFERENCES Pool(PoolID),
	RaceID			UNIQUEIDENTIFIER	FOREIGN KEY	REFERENCES Race(RaceID),
	);

CREATE TABLE HorseInRace(
	EntryID			UNIQUEIDENTIFIER	PRIMARY KEY,
	HorseID			UNIQUEIDENTIFIER	FOREIGN KEY REFERENCES Horse(HorseID),
	RaceID			UNIQUEIDENTIFIER	FOREIGN KEY REFERENCES Race(RaceID),
	JockeyName		NVARCHAR(100),
	Name			NVARCHAR(20),
	Number			INT,
	Scratched		INT,
	Barrier			NVARCHAR(5),
	JockeyWeight	DECIMAL,
	JockeyAllowance	NVARCHAR(10)
	);
	
CREATE TABLE HorseInBet(
	HorseBetID		UNIQUEIDENTIFIER	PRIMARY KEY,
	EntryID			UNIQUEIDENTIFIER	FOREIGN KEY REFERENCES HorseInRace(EntryID)
	);
	
CREATE TABLE BetLines(
	BetLineID		UNIQUEIDENTIFIER	PRIMARY KEY,
	HorseInBetID	UNIQUEIDENTIFIER	FOREIGN KEY REFERENCES HorseInBet(HorseBetID),
	BetID			UNIQUEIDENTIFIER					FOREIGN KEY REFERENCES Bet(BetID),
	Position		INT					Not Null
	);

	--ROLLBACK

	COMMIT