//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WagerWatcher {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Constants {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Constants() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WagerWatcher.Constants", typeof(Constants).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entry.
        /// </summary>
        internal static string horseInRaceRoot {
            get {
                return ResourceManager.GetString("horseInRaceRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to meeting.
        /// </summary>
        internal static string meetingRoot {
            get {
                return ResourceManager.GetString("meetingRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://xml.tab.co.nz/odds/.
        /// </summary>
        internal static string oddsDownload {
            get {
                return ResourceManager.GetString("oddsDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to option.
        /// </summary>
        internal static string optionRoot {
            get {
                return ResourceManager.GetString("optionRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://xml.tab.co.nz/pools/.
        /// </summary>
        internal static string poolsDownload {
            get {
                return ResourceManager.GetString("poolsDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://xml.tab.co.nz/qla/.
        /// </summary>
        internal static string quenellaDownload {
            get {
                return ResourceManager.GetString("quenellaDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to race.
        /// </summary>
        internal static string raceRoot {
            get {
                return ResourceManager.GetString("raceRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://xml.tab.co.nz/results/.
        /// </summary>
        internal static string resultsDownload {
            get {
                return ResourceManager.GetString("resultsDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://xml.tab.co.nz/schedule/.
        /// </summary>
        internal static string scheduleDownload {
            get {
                return ResourceManager.GetString("scheduleDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://xml.tab.co.nz/will-pay/.
        /// </summary>
        internal static string willPayDownload {
            get {
                return ResourceManager.GetString("willPayDownload", resourceCulture);
            }
        }
    }
}
